version: "3.7"

services:
  app:
    build: .
    container_name: spring_boot_app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/fleetflow
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Zakaria@741
    networks:
      - app_network

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    ports:
      - 3307:3306
    networks:
      - app_network
    environment:
      MYSQL_DATABASE: fleetflow
      MYSQL_ROOT_PASSWORD: Zakaria@741
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pZakaria@741"]
      timeout: 5s
      retries: 10
      interval: 10s

networks:
  app_network:

volumes:
  db_data: