services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 230223
      MYSQL_DATABASE: fleetflow3
    ports:
        - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - fleetflow-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  fleetflow-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fleetflow-api
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/fleetflow3
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 230223
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_JPA_SHOW_SQL: "true"
    ports:
      - "8080:8080"
    networks:
        - fleetflow-network

volumes:
    mysql_data:
      driver: local


networks:
    fleetflow-network:
        driver: bridge