CREATE TABLE client(
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    nom VARCHAR(20) NOT NULL,
    email VARCHAR(50) UNIQUE NOT NULL,
    telephone VARCHAR(10) NOT NULL,
    ville VARCHAR(10) NOT NULL
);

CREATE TABLE vehicule(
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    capacite INT NOT NULL,
    matricule VARCHAR(40) UNIQUE NOT NULL,
    status ENUM('DISPONIBLE', 'EN_LIVRAISON', 'MAINTENANCE') DEFAULT 'DISPONIBLE' NOT NULL,
    type VARCHAR(20) NOT NULL
);

CREATE TABLE chauffeur(
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    nom VARCHAR(20) NOT NULL,
    telephone VARCHAR(10) UNIQUE NOT NULL,
    permis_type VARCHAR(30) NOT NULL,
    disponible BOOLEAN
);

CREATE TABLE livraison(
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    date_livraison DATETIME NOT NULL,
    adresse_depart VARCHAR(30) NOT NULL,
    adresse_destination VARCHAR(30) NOT NULL,
    statut ENUM('EN_ATTENTE', 'EN_COURS', 'LIVREE') DEFAULT 'EN_ATTENTE',
    client_id BIGINT,
    vehicule_id BIGINT,
    chauffeur_id BIGINT
);


