name: fleetflow Partie 4

on:
  push:
    branches: [ "marouane" ]
  pull_request:
    branches: [ "marouane" ]
jobs:
  built-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: 230223
          MYSQL_DATABASE: fleetflow4
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: maven
      - name: Test with mvn
        run: mvn test

      - name: Build mvn
        run: mvn package -DskipTests
